### ISSUE TITLE
Page Slicing Parameters

### ISSUE THREAD

**Issue by pedroliborio** [imec-idlab/IEEE-802.11ah-ns-3#9] opened 2019-05-17 21:51 UTC
Hi guys, 

Firstly I would like to thank for the fabulous work you have done about 802.11ah.
I started an implementation of heterogeneous applications in order to evaluate networking slicing mechanisms.
Actually, I am getting this error, but I don't know exactly why.

`assert failed. cond="m_pageSlice.GetPageindex() == m_TIM.GetPageIndex()", file=../src/wifi/model/sta-wifi-mac.cc, line=407

I had followed the instructions to configure a single page slice: pageSliceCount=0 and pageSliceLength = 1.
Could you guys help-me?

This is  the input file:
[rawconfig-slicing-1-3-2-6.txt]
Meaning 1 RPS, 3 RAW Groups, 2 slots per RAW Group and a total of 6 nodes (2 per RAW).
(https://github.com/imec-idlab/IEEE-802.11ah-ns-3/files/3193195/rawconfig-slicing-1-3-2-6.txt)

This is the "paging" configurations changed in Configuration.h
`
pagePeriod=1; 
pageIndex=0;
pageSliceLength=1; 
pageSliceCount=0;
blockOffset = 0;  	
timOffset = 0;    	
`

Thank you for any feedback.

Cheers,
Pedro.

**Comment by asljivo1** [comment] 2019-05-20 08:29
Hi Pedro,

We have heared of this issue before but none of us could ever reproduce this error which makes it hard to fix it. We cannot precisely debug the program without the error, but we would appreciate very much if you could contribute to fixing it once and for all. 

Before I get on with what might cause this (if you are interested in trying to find where the missassignment occurs, to properly fix the issue), there is a **workaround**: you can comment line 407, I the program will still work correctly.

I suspect the problem is that page index is uninitialized somewhere, and my compiler initializes it with 0 (accidentally the correct value), whereas yours doesn't. It can happen either for m_pageSlice or m_TIM (both should equal zero in the test simulation). Could you please let me know which system and which compiler you use for running ns-3? We have run it on Linux Ubuntu 16.04.6 LTS (xenial) and on Mac OS High Sierra, and that error never occured. I have tried g++ and clang compiler on Ubuntu (clang on MAC OS).

Try adding line m_TIM.SetPageIndex (m_PageIndex); just before beacon.SetTIM (m_TIM); in ApWifiMac. Does it make any difference?

In scratch/test/s1g-test-tim-raw.cc in functions configurePageSlice() and configureTIM() page index is set to 0 (setting for <=2048 stations where tim offset = 0). Please make sure they are set to 0 in your code. These configurations are passed to ApWifiMac through ns-3 attributes TIMSet and PageSliceSet and stored in attributes m_TIM and m_pageslice respectively. ApWifiMac manipulates with m_TIM and m_pageslice and encodes them into beacons. TIM element and page slice element are serialized in src/wifi/model/tim.cc and src/wifi/model/pageSlice.cc, so print out the serialized value and the deserialized value of page index in pageSlice::SerializeInformationField, pageSlice::DeserializeInformationField, TIM::SerializeInformationField and TIM::DeserializeInformationField. What are the printed values? At least one has to be different from 0. From here we will know where to look for the bug further. If you can watch the two attributed in debug mode during runtime and pinpoint when and where exactly they change, that would probably solve the mystery. 

We would very much appreciate if you could look into this for us and find where a non-zero value gets assigned to either m_TIM's or m_pageSlice's page index. The field might get overwritten somewhere, or incorrectly serialized or deserialized. If not, the workaround will work for less than 2048 stations.

Good luck,
Amina

**Comment by pedroliborio** [comment] 2019-05-20 13:16
Hi Amina,
Thank you for the fast feedback, I just commented the line 407 and the program does not stop anymore.

I will try to make the proposed steps to find the cause of the problem. Once I have finished I will post the results here.

Surprising the error begun occurs some days ago. Before, the simulator was running perfectly.

Cheers,
Pedro.

**Closed** 2019-05-23 12:26 UTC
